pub mod c_config;
pub mod c_color;
pub mod c_canvas;
pub mod c_rectangle;
pub mod t_drawable;
pub mod c_input;
pub mod c_player;
pub mod t_updatable;
pub mod t_entity;
pub mod t_collision;
pub mod c_rect_collider;
pub mod c_ball;
pub mod c_player_bot;
pub mod c_world_context;
pub mod c_scoreboard;
pub mod e_current_scene;
pub mod scenes;
mod UI;